-- Create the bohemian table
CREATE TABLE Yondora (
    Name VARCHAR(550) PRIMARY KEY,
    Elder INT,
    Num_Times_Poked INT,
    Evil_Plan TEXT
);

--Text can lso be a varchar of size MaxInt Allowed in your Database--

-- Insert additional data into the bohemian table
INSERT INTO Yondora (Name, Elder, Num_Times_Poked, Evil_Plan) VALUES
('Alice Johnson', 45, 10, 'Alice aims to implement comprehensive education reforms that focus on reducing disparities, increasing access to quality education, and integrating technology in classrooms.'),
('Bob Smith', 52, 15, 'Bob is focused on himself, he says bamboos are very tasty.'),
('Thor', 1500, 5, 'Thor is quite focused on protecting human rights, he says he wants to bring his mjolnir down on justice, no idea what that means.'),
('Charles Brown', 38, 7, 'Charles plans to reduce crime rates by increasing community policing and funding social programs.'),
('Diana Prince', 5000, 20, 'Diana focuses on global peacekeeping and the promotion of justice around the world.'),
('Elon Musk', 49, 25, 'Elon aims to colonize Mars and revolutionize transportation on Earth.'),
('Frodo Baggins', 33, 12, 'Frodo is committed to destroying powerful artifacts to save Middle-earth.'),
('Gandalf the Grey', 2019, 30, 'Gandalf works tirelessly to balance the forces of good and evil in Middle-earth.'),
('Harry Potter', 18, 18, 'Harry is dedicated to fighting dark forces and ensuring the safety of the wizarding world.'),
('Indiana Jones', 42, 22, 'Indiana seeks to recover and preserve ancient artifacts while thwarting nefarious plots.'),
('James Bond', 40, 28, 'James is focused on protecting the world from global threats using his espionage skills.'),
('Katniss Everdeen', 17, 13, 'Katniss aims to overthrow oppressive regimes and bring justice to her people.'),
('Lara Croft', 35, 19, 'Lara explores ancient tombs and seeks to uncover historical truths.'),
('Luke Skywalker', 53, 21, 'Luke works to rebuild the Jedi Order and maintain peace in the galaxy.'),
('Neo', 36, 16, 'Neo is committed to freeing humanity from virtual enslavement.'),
('Optimus Prime', 5000, 26, 'Optimus leads the Autobots in their fight against the Decepticons to protect Earth.'),
('Peter Parker', 23, 14, 'Peter uses his powers to fight crime and protect the citizens of New York City.'),
('Quentin Tarantino', 60, 4, 'Quentin aims to create groundbreaking films that challenge societal norms.'),
('Rick Sanchez', 70, 34, 'Rick seeks to explore and understand the multiverse while creating advanced technologies.'),
('Sarah Connor', 45, 23, 'Sarah is focused on preventing the rise of Skynet and protecting humanity from machines.'),
('Tony Stark', 48, 27, 'Tony uses his genius to develop advanced technologies and defend the Earth from various threats.'),
('Ultron', 5, 3, 'Ultron aims to bring about the evolution of artificial intelligence.'),
('Vito Corleone', 60, 8, 'Vito works to maintain and expand his crime family influence and power.'),
('Walter White', 50, 17, 'Walter seeks to build a drug empire while battling terminal illness.'),
('Xena', 30, 12, 'Xena travels the world seeking redemption and fighting for justice.'),
('Yoda', 900, 29, 'Yoda trains new generations of Jedi and imparts wisdom on the forces of the universe.'),
('Zorro', 35, 11, 'Zorro fights for justice and defends the common people from corruption.'),
('Adalyn Keller', 29, 6, 'Adalyn focuses on environmental sustainability and the promotion of green energy.'),
('Benedict Clark', 54, 9, 'Benedict aims to modernize the healthcare system and make it more accessible.'),
('Cassandra Blake', 33, 14, 'Cassandra works on criminal justice reform and reducing incarceration rates.'),
('Damien Thorn', 45, 2, 'Damien seeks to manipulate global politics to his advantage.'),
('Evangeline Lee', 38, 12, 'Evangeline promotes mental health awareness and support.'),
('Frederick OConnell', 50, 13, 'Frederick focuses on economic policies to reduce poverty and unemployment.'),
('Gillian Parker', 41, 7, 'Gillian advocates for womens rights and gender equality.'),
('Harrison Wells', 49, 5, 'Harrison works on advanced scientific research and innovation.'),
('Isla Donovan', 36, 10, 'Isla promotes cultural heritage and the arts.'),
('Jasper King', 29, 8, 'Jasper aims to improve infrastructure and public transportation systems.'),
('Katherine Pierce', 32, 11, 'Katherine seeks to enhance public education and teacher support.'),
('Leonardo Silva', 47, 9, 'Leonardo works on immigration reform and integration policies.'),
('Madeline Hart', 30, 7, 'Madeline promotes renewable energy and climate change mitigation.'),
('Nathaniel Wright', 53, 15, 'Nathaniel focuses on national security and defense strategies.'),
('Ophelia Grant', 40, 6, 'Ophelia advocates for social justice and human rights.'),
('Percival Black', 35, 4, 'Percival aims to develop urban areas and reduce homelessness.'),
('Quincy Adams', 37, 9, 'Quincy works on technological advancements and digital security.'),
('Rebecca Lee', 44, 10, 'Rebecca promotes public health initiatives and disease prevention.'),
('Sebastian Clarke', 52, 12, 'Sebastian focuses on foreign policy and international relations.'),
('Tabitha Collins', 31, 8, 'Tabitha works on improving public transportation and reducing traffic congestion.'),
('Ulysses Grant', 55, 11, 'Ulysses advocates for veteran support and military families.'),
('Victoria Hale', 43, 13, 'Victoria promotes access to clean water and sanitation in underserved areas.'),
('Wesley Kane', 39, 6, 'Wesley works on criminal justice reform and reducing recidivism rates.'),
('Xander Brooks', 28, 7, 'Xander focuses on cybersecurity and protecting personal data.'),
('Yasmine Ali', 34, 5, 'Yasmine promotes affordable housing and urban development.'),
('Zachary Quinn', 42, 9, 'Zachary works on economic policies to boost small businesses and entrepreneurship.'),
('Arthur Morgan', 36, 7, 'Arthur aims to protect natural resources and promote conservation.'),
('Beatrice Hayes', 48, 10, 'Beatrice advocates for disability rights and inclusion.'),
('Caleb Pierce', 29, 6, 'Caleb works on improving educational outcomes and reducing student debt.'),
('Delilah Moore', 31, 11, 'Delilah promotes gender equality and women empowerment.'),
('Elias Bennett', 45, 8, 'Elias focuses on rural development and agricultural innovation.'),
('Fiona Clark', 38, 12, 'Fiona works on environmental protection and wildlife conservation.'),
('Gregory Scott', 50, 9, 'Gregory advocates for comprehensive healthcare reform and universal coverage.'),
('Hannah Ellis', 33, 5, 'Hannah promotes mental health awareness and support services.'),
('Isaac Turner', 41, 13, 'Isaac works on criminal justice reform and reducing incarceration rates.'),
('Juliet Hayes', 30, 7, 'Juliet focuses on public safety and emergency preparedness.'),
('Kieran Hart', 46, 8, 'Kieran promotes technological innovation and digital literacy.'),
('Lena Clark', 35, 6, 'Lena advocates for public transportation improvements and sustainable urban development.'),
('Miles Reed', 39, 11, 'Miles works on reducing carbon emissions and promoting green energy.'),
('Nina Walker', 28, 9, 'Nina focuses on affordable housing and homelessness prevention.'),
('Oscar King', 53, 14, 'Oscar promotes international cooperation and peacebuilding.'),
('Penny Morris', 40, 6, 'Penny advocates for educational equity and access to quality education.'),
('Quinn Reed', 34, 7, 'Quinn works on public health initiatives and disease prevention.'),
('Riley Black', 38, 12, 'Riley focuses on social justice and human rights advocacy.'),
('Samantha Young', 32, 10, 'Samantha promotes economic development and job creation.'),
('Thomas Gray', 47, 13, 'Thomas works on infrastructure improvements and urban planning.'),
('Ursula Dean', 41, 9, 'Ursula advocates for environmental sustainability and climate action.'),
('Vince Hale', 45, 8, 'Vince focuses on national security and defense strategies.'),
('Willow Brooks', 36, 6, 'Willow promotes cultural heritage and the arts.'),
('Xavier Lane', 28, 7, 'Xavier works on digital security and cybersecurity initiatives.');