# Use the official Python image as a base
FROM python:3.8

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Django project into the container
COPY . .

# Run migrations
RUN python manage.py migrate

# Start the Django development server with hot reloading
CMD ["watchmedo", "auto-restart", "--directory=./", "--recursive", "--", "python", "manage.py", "runserver_plus", "0.0.0.0:8000"]
